name: Release

on:
  push:
    tags: ["*"]

permissions:
    id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - uses: abatilo/actions-poetry@v2

      - run: poetry config virtualenvs.create true --local && poetry config virtualenvs.in-project true --local

      - uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - run: poetry install

      - run: poetry build

      - uses: pypa/gh-action-pypi-publish@release/v1

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
